### ISSUE TITLE
Atouts bouclier

### ISSUE THREAD

**Issue by FenrisM** [Torgan/sawo-fr#435]
Remplacer les atouts Expert et maître en bouclier
proposition
Expert en bouclier : ne subit plus le malus d'Arme improvisée, dégâts For+d4 (petit et moyen) ou +d6 (grand), y compris pour Repousser.`

**Comment by XOdeVorcen** [comment]
Fait dans le seul profil utilisant ces atouts (Murq) et dans Atouts et Capacités. Pas de changement dans le répertoire Atouts.

**Comment by FenrisM** [comment]
ça peut être une option intéressante à ajouter pour les joueurs cependant, mais je clos ;)
